model:
  num_classes: 4
  input_channels: 1
  num_layers: 1
  kernel_size: 3
  dropout_rate: 0.5

training:
  seed: 42
  num_epochs: 50
  batch_size: 16
  learning_rate: 0.001
  patience: 5
  val_split: 0.2

hydra:
  sweeper:
    params:
      # training.batch_size: choice(16,32,64)
      # training.learning_rate: choice(0.01,0.001,0.0001)
      model.dropout_rate: choice(0.5,0.9)
      # model.num_layers: choice(1,3,5,7)

data:
  train_data_path: data/processed/train
  train_metadata_path: data/processed/metadata_train.csv

dummy_input:
  batch_size: 8
  n_mels: 128
  seq_len: 200

logging:
  level: INFO  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  training_log: logging/training.log

paths:
  model_save: models/best_cnn_audio_classifier.pt
  figures: reports/figures

wandb:
  project: instrument_classifier
  entity: null  # Set your wandb entity here if needed
